# Generated by Django 5.0.5 on 2024-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language_object',
            field=models.ManyToManyField(to='books.language'),
        ),
    ]
